### PR TITLE
CI: update OS versions

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

building macOS env takes now about 20min and mostly because of building `grpcio`

## Before submitting

- [ ] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by SkafteNicki — APPROVED** [review]

**Comment by Borda** [comment]
not sure why, but some random tests on macOS are TO for 180sec

**Comment by Borda** [comment]
This is suspicious that just changing the OS version some tests start to fail... :/

**Comment by Borda** [comment]
@justusschock could you try to replicate the failing tests (seems failing only on Mac)

**Review by stancld — APPROVED** [review]

**Comment by Borda** [comment]
let's leave it unless it becomes an issue... :otter:

**Pull request closed without merging**
