### PR TITLE
tests: copy no call helper

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

copy `no_warning_call` so integration has no dependency on unittests

## Before submitting

- [ ] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by justusschock — COMMENTED** [review]
Implementation lgtm, but why is a dependency on unittest bad? This is builtin and we use it all the time (also for mocking)

**Comment by Borda** [comment]
> Implementation lgtm, but why is a dependency on unittest bad? This is builtin and we use it all the time (also for mocking)

Implementation is just copy-paste :)

Well, it is tricky as for a single function, you need to post all unittests... so the trade-off is to have integrations independent (needed for Ecosystem-CI) vs. having a 1:1 copy of the same function :)

**Review by justusschock — APPROVED** [review]
But let's add credits to unittest

**Comment by Borda** [comment]
> But let's add credits to unittest

it is our unittests :)
https://github.com/Lightning-AI/metrics/blob/master/tests/unittests/helpers/utilities.py

**Pull request merged**
