### PR TITLE
use future annotation

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

lets cleen the codebase a bit: https://stackoverflow.com/a/33533514/4521646

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by SkafteNicki** [comment]
@Borda what about dropping python 3.7?

**Comment by stancld** [comment]
@Borda Have you adopted this new typing in `lightning`? I'm not sure how common it is used and not sure if it can't be confusing for some contributors. We use future annotations as well, but still sticks to the hints from `typing`, but leverage `TYPE_CHECKING` to postpone some imports only for type checking, which are not then imported in program runtime.

**Comment by Borda** [comment]
> I'm not sure how common it is used and not sure if it can't be confusing for some contributors. We use future annotations as well, but still sticks to the hints from `typing`

Good question, I beilve that typing from one package (dependency) shall not affect other typing...

**Comment by Borda** [comment]
Anyway this is chnaging on minor part of our codebase, so if we go with it, then lets do it everywhere... What I did is just add the `from __future__ import annotations` to the file, and the rest was handled by our bot :robot: 
cc: @Lightning-AI/core-metrics @SkafteNicki @justusschock

**Comment by SkafteNicki** [comment]
I am fine with this change :)

**Comment by Borda** [comment]
lets leve it for another time as @carmocca mentioned in https://github.com/Lightning-AI/utilities/pull/109#pullrequestreview-1307790679

**Pull request closed without merging**
